<!DOCTYPE html>
<html lang="sl">
<head>
    <meta charset="UTF-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Storitve | FITMENTOR</title>
	<meta name="description" content="">
	<meta name="keywords" content="">

    <!-- Font Awesome if you need it
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
	-->
  <link rel="stylesheet" href="https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/css/main.ad49aa9b.css" />
        <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
        <link rel="shortcut icon" type="image/x-icon" href="{{ asset('favicon.ico') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nunito&family=Raleway:wght@500&family=Roboto+Mono:wght@500&family=Space+Mono&family=Titillium+Web&display=swap" rel="stylesheet">

	<!--Replace with your tailwind.css once created-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/3.8.1/cdn.min.js" defer></script>

	<!-- Animation CSS-->
	<style>
    *{
      font-family: 'Titillium Web', sans-serif;
    }
		 /* ----------------------------------------------
		 * Generated by Animista
		 * w: http://animista.net, t: @cssanimista
		 * ---------------------------------------------- */

		.slide-in-bottom{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both}
		.slide-in-bottom-h1{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both}
		.slide-in-bottom-subtitle{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both}
		.fade-in{-webkit-animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both;animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both}
		.bounce-top-icons{-webkit-animation:bounce-top .9s 1s both;animation:bounce-top .9s 1s both}

		@-webkit-keyframes slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}@keyframes slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}
		@-webkit-keyframes bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}@keyframes bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}
		@-webkit-keyframes fade-in{0%{opacity:0}100%{opacity:1}}@keyframes fade-in{0%{opacity:0}100%{opacity:1}}

	</style>
</head>

    <body class="leading-normal tracking-normal text-gray-900 bg-gray-200 max-w-12xl mx-auto sm:px-6 lg:px-0" style="">

            <div class="w-full pt-4 sm:px-4 lg:px-10 bg-gray-900 overflow-x-auto">
              <div class="flex justify-between ">
                <div class="flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-blue-500" fill="none" viewBox="0 0 20 20" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.989,9.491L6.071,0.537C5.78,0.246,5.308,0.244,5.017,0.535c-0.294,0.29-0.294,0.763-0.003,1.054l8.394,8.428L5.014,18.41c-0.291,0.291-0.291,0.763,0,1.054c0.146,0.146,0.335,0.218,0.527,0.218c0.19,0,0.382-0.073,0.527-0.218l8.918-8.919C15.277,10.254,15.277,9.784,14.989,9.491z" />
                  </svg>
                  <span class="ml-2 text-2xl font-semibold text-white"><a href="/services">FITMENTOR</a></span>
                </div>

              <div class="ml-6 flex flex-1 gap-x-3">


                <!-- Show this component on mobile -->
                <div class="block md:hidden">
                 </div>

                <!-- Show this component on desktop -->
                <div class="hidden md:flex">

                    <div class="icon-bar flex mt-3 text-white">
                      <a class="active" href="{{ route('services') }}"><i class="fa fa-home ml-2 mr-2"></i></a>
                      <a href="{{ route('dashboard') }}"><i class="fa fa-plus ml-2 mr-2"></i></a>
                      <a href="{{ route('about') }}"><i class="fa fa-edit ml-2 mr-2"></i></a>
                    </div>



                  <form class="w-full rounded-md px-3 py-1 flex items-center" action="{{url('type')}}" method="get">
                  <p class="pr-2 text-white">></p>
                  <select id="type" name="search" class="w-full rounded-md border border-[#DDE2E4] px-3 py-2 text-sm" type="{{ url('search') }}" name="type">
                    @php
                        $dropdownValues = ['Izguba telesne teže',
                    'Pridobitev mišične mase',
                    'Vzdržljivost in kondicija',
                    'Zdrav življenjski slog',
                    'Sprostitvena vadba',
                    'Vadba za moč',
                    'Fitnes studio',
                    'Osebni trener',
                    'Drugo'];
                    @endphp

                    @foreach($dropdownValues as $value)
                        <option value="{{ $value }}">{{ $value }}</option>
                    @endforeach
                  </select>
                  <button type="submit" class="ml-2 btn btn-primary" style="color:white">
                <i class="fa fa-search"></i>
                  </button>
                  </form>

                  <form class="w-full rounded-md px-3 py-1 flex items-center" action="{{url('region')}}" method="get">
                  <p class="pr-2 text-white">></p>
                  <select id="region" name="search" class="w-full rounded-md border border-[#DDE2E4] px-3 py-2 text-sm" type="{{ url('search') }}">
                    @php
                        $dropdownValues = ['Gorenjska',
                    'Goriška',
                    'Jugovzhodna Slovenija',
                    'Koroška',
                    'Notranjsko-kraška',
                    'Obalno-kraška',
                    'Osrednjeslovenska',
                    'Podravska',
                    'Pomurska',
                    'Posavska',
                    'Primorsko-notranjska',
                    'Savinjska',
                    'Zasavska'];
                    @endphp
                    @foreach($dropdownValues as $value)
                        <option value="{{ $value }}">{{ $value }}</option>
                    @endforeach
                  </select>
                  <button type="submit" class="ml-2 btn btn-primary" style="color:white">
                <i class="fa fa-search"></i>
                  </button>
                  </form>

                  <form class="w-full rounded-md px-3 py-1 flex items-center" action="{{url('search')}}" method="get">
                  <p class="pr-2 text-white">></p>
                  <input type="{{ url('search') }}" name="search" class="w-full rounded-md border border-[#DDE2E4] px-3 py-2 text-sm" placeholder="Naziv storitve..." />
                  <button type="submit" class="ml-2 btn btn-primary" style="color:white">
                <i class="fa fa-search"></i>
                  </button>

                  </form>
          </div>
                  </div>


                <div class="ml-2 flex">
                  @auth
                  <div class="ml-2 flex cursor-pointer items-center gap-x-1 rounded-md border py-2 px-4 bg-blue-600 text-white hover:bg-gray-100 hover:text-black">
                    <a href="/dashboard"><span class="text-sm font-medium">Domov</span></a>
                  </div>

                  @else
                  <div class="ml-2 flex cursor-pointer items-center gap-x-1 rounded-md border py-2 px-4 hover:bg-gray-700">
                    <a href="/login"><span class="text-sm font-medium text-white">Prijava</span></a>
                  </div>

                  <div class="ml-2 flex cursor-pointer items-center gap-x-1 rounded-md border py-2 px-4 text-black bg-white hover:bg-gray-300 hover:text-black">
                    <a href="/register"><span class="text-sm font-medium">Registracija</span></a>
                  </div>
                </div>
                @endauth
              </div>

              <div class="mt-4 flex items-center justify-between">
                <div class="flex gap-x-2 py-1 pl-1">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-0 w-0 text-gray-500" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
                  </svg>
                </div>

              </div>
            </div>
          </div>

            @foreach($all as $a)
                {{$a->type}}
                @endforeach

          <div class="w-full">
            <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">
                <div class="text-center pb-12">
                    <h2 class="text-base font-bold text-black mt-2 mb-2">
                        Uresničite vaše cilje za 2024 pod vodstvom kompetenčnega in vztrajnega mentorstva na področju športa in fitnesa.
                    </h2>
                    <h1 class="font-bold text-3xl md:text-4xl lg:text-5xl font-heading text-black">
                        FITMENTOR ŠPORTNO-MENTORSKE DEJAVNOSTI
                    </h1>
                </div>
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <div class="w-full bg-gray-900 rounded-lg sahdow-lg p-12 flex flex-col justify-center items-center">
                        <div class="mb-8">
                            <img class="object-center object-cover rounded-full h-36 w-36" src="https://cdn.pixabay.com/photo/2017/04/25/20/18/woman-2260736_960_720.jpg" alt="photo">
                        </div>
                        <div class="text-center">
                            <p class="text-xl text-white font-bold mb-2">Osebni treningi</p>
                            <p class="text-base text-gray-400 font-normal">Prebrskajte naš katalog pooblaščenih trenerjev na področju športa in fitnesa</p>
                        </div>
                    </div>
                    <div class="w-full bg-gray-900 rounded-lg sahdow-lg p-12 flex flex-col justify-center items-center">
                        <div class="mb-8">
                            <img class="object-center object-cover rounded-full h-36 w-36" src="https://cdn.pixabay.com/photo/2016/02/05/19/21/gym-room-1181822_960_720.jpg" alt="photo">
                        </div>
                        <div class="text-center">
                            <p class="text-xl text-white font-bold mb-2">Fitnes lokacije</p>
                            <p class="text-base text-gray-400 font-normal">Preveri najboljše ponudbe fitnes lokacij v Sloveniji glede na kakovost in ceno</p>
                        </div>
                    </div>
                    <div class="w-full bg-gray-900 rounded-lg sahdow-lg p-12 flex flex-col justify-center items-center">
                        <div class="mb-8">
                            <img class="object-center object-cover rounded-full h-36 w-36" src="https://cdn.pixabay.com/photo/2023/09/26/09/08/weightlifting-8276951_960_720.jpg" alt="photo">
                        </div>
                        <div class="text-center">
                            <p class="text-xl text-white font-bold mb-2">Posredništvo</p>
                            <p class="text-base text-gray-400 font-normal">Z vpisom v našo evidenco oglašujte vaše športne storitve brezplačno</p>
                        </div>
                    </div>
                </div>
            </section>
        </div>

            <!-- Desktop -->
            <div class="hidden md:block border-t border-gray-300 mb-6">
                <h1 class="text-3xl font-semibold text-gray-900 text-center mb-4 mt-2">Kakšni so vaši cilji?</h1>
                <div class="ml-12 mr-12" style="display:grid;">
                    <div class="flex flex-row">
                        <div class="flex flex-col justify-center items-center w-80 ml-6">
                            <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
                                <div class="h-full w-full">
                                    <div class="relative w-full">
                                        <img src="https://cdn.pixabay.com/photo/2021/01/13/16/46/workout-5914643_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
                                        <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-500 p-2 text-brand-500 hover:cursor-pointer">
                                        </button>
                                    </div>
                                    <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                                        <div class="mb-2">
                                            <p class="text-lg font-bold text-navy-700"> Izgubiti težo </p>
                                        </div>
                                        <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                                            <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🏃🏼‍♀️</span>
                                        </div>
                                    </div>
                                    <div class="flex items-center justify-between md:items-center lg:justify-between ">
                                        <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Turizem">Išči</a></button>
                                    </div>
                                </div>
                            </div>


                        </div>

                        <!-- COMPONENT START -->
                        <div class="flex flex-row">
                            <div class="flex flex-col justify-center items-center w-80 ml-6">
                                <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
                                    <div class="h-full w-full">
                                        <div class="relative w-full">
                                            <img src="https://cdn.pixabay.com/photo/2015/11/01/19/45/weights-1017465_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
                                            <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-500 p-2 text-brand-500 hover:cursor-pointer">
                                            </button>
                                        </div>
                                        <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                                            <div class="mb-2">
                                                <p class="text-lg font-bold text-navy-700"> Pridobiti mišično maso </p>
                                            </div>
                                            <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                                                <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🏋️‍♀️</span>
                                            </div>
                                        </div>
                                        <div class="flex items-center justify-between md:items-center lg:justify-between ">
                                            <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Izobraževanje">Išči</a></button>
                                        </div>
                                    </div>
                                </div>
                            </div>




                        </div>
                        <!-- HERE -->
                        <div class="" style="display:grid;">
                            <div class="flex flex-row">
                                <div class="flex flex-col justify-center items-center w-80 ml-6">
                                    <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
                                        <div class="h-full w-full">
                                            <div class="relative w-full">
                                                <img src="https://cdn.pixabay.com/photo/2017/04/26/09/44/sport-2262083_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
                                                <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-500 p-2 text-brand-500 hover:cursor-pointer">
                                                </button>
                                            </div>
                                            <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                                                <div class="mb-2">
                                                    <p class="text-lg font-bold text-navy-700"> Povečati vzdržljivost </p>
                                                </div>
                                                <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                                                    <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🚴‍♀️</span>
                                                </div>
                                            </div>
                                            <div class="flex items-center justify-between md:items-center lg:justify-between ">
                                                <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Rekreacija%2C+šport">Išči</a></button>
                                            </div>
                                        </div>
                                    </div>


                                </div>

                                <!-- COMPONENT START -->
                                <div class="flex flex-row">
                                    <div class="flex flex-col justify-center items-center w-80 ml-6">
                                        <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
                                            <div class="h-full w-full">
                                                <div class="relative w-full">
                                                    <img src="https://cdn.pixabay.com/photo/2015/07/02/10/27/training-828764_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
                                                    <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-300 p-2 text-brand-500 hover:cursor-pointer">
                                                        <div class="flex h-full w-full items-center justify-center rounded-full text-xl hover:bg-gray-50">
                                                        </div>
                                                    </button>
                                                </div>
                                                <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                                                    <div class="mb-2">
                                                        <p class="text-lg font-bold text-navy-700"> Zdrav življenski slog </p>
                                                    </div>
                                                    <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                                                        <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🤸‍♂️</span>
                                                    </div>
                                                </div>
                                                <div class="flex items-center justify-between md:items-center lg:justify-between ">
                                                    <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Avto-moto">Išči</a></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>




                                </div>


                            </div>
                        </div>
                        <!-- END HERE -->
                        <div class="" style="display:grid;">
                            <div class="flex flex-row">
                                <div class="flex flex-col justify-center items-center w-80 ml-6">
                                    <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
                                        <div class="h-full w-full">
                                            <div class="relative w-full">
                                                <img src="https://cdn.pixabay.com/photo/2016/11/29/12/17/action-1869428_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
                                                <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-300 p-2 text-brand-500 hover:cursor-pointer">
                                                    <div class="flex h-full w-full items-center justify-center rounded-full text-xl hover:bg-gray-50">
                                                    </div>
                                                </button>
                                            </div>
                                            <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                                                <div class="mb-2">
                                                    <p class="text-lg font-bold text-navy-700"> Športno treniranje </p>
                                                </div>
                                                <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                                                    <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🤾‍♀️</span>
                                                </div>
                                            </div>
                                            <div class="flex items-center justify-between md:items-center lg:justify-between ">
                                                <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Pravne+storitve">Išči</a></button>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>

          <!-- FIRST HEADER-->
            @php
            $st_list = 0;
            @endphp

            @foreach($services as $service)
                @php
                $st_list++;
                @endphp
            @endforeach

          <div class="mt-2 border-t border-b border-gray-300 text-center">
            <h1 class="text-3xl text-center border font-semibold text-black mt-6 mb-1">
              Prebrskaj evidenco pooblaščenih osebnih trenerjev
            </h1>
              <p class="text-xl font-bold text-black mb-4">Trenutno št. aktivnih osebnih trenerjev: {{$st_list}} </p>

            <!-- MOBILE -->
            <div class="block md:hidden">
              <form class="w-full rounded-md px-3 py-1 flex items-center" action="{{url('search')}}" method="get">
                <input type="{{ url('search') }}" name="search" class="w-full rounded-md border border-[#DDE2E4] px-3 py-3 text-md" placeholder="Vpiši naziv osebe..." />
                <button type="submit" class="mx-2 btn btn-primary" style="color:black">
                <i class="fa fa-search"></i>
                </button>
                </form>
            </div>

            <!-- DESKTOP -->
            <div class="hidden md:block">
              <form class="w-full rounded-md px-3 py-1 absolute-center items-center" action="{{url('search')}}" method="get">
                <input type="{{ url('search') }}" name="search" class="w-80 rounded-md border border-[#DDE2E4] px-3 py-3 text-md" placeholder="Vpiši naziv osebe..." >
                <button type="submit" class="btn btn-primary" style="color:black;">
                <i class="fa fa-search"></i>
                </button>
                </form>

            </div>

            <br />
          </div>

          <div class="border-b border-gray-300">
              <!-- ŠTEVCI ZA LOOP -->
                  @php
                  $inc = 0; // št. skupnih rezultatov
                  $cnt = 0; // št. rezultatov pod "osebni trener"
                  $tnc = 0; // št. rezultatov pod "fitnes"
                  @endphp

                    @foreach($services as $service)
                    @php
                    $inc++;
                    @endphp

                    @if($service->type == 'Osebni trener')
                    @php
                    $cnt++;
                    @endphp

                    @elseif($service->type == 'Fitnes studio')
                    @php
                    $tnc++;
                    @endphp

                    @endif
                    @endforeach

            <!-- <div class="flex flex-row"> row alineje cardov-->

              <div class="max-w-3xl mx-auto my-10">
                <div class="bg-gray-900 shadow-lg rounded-lg p-6 space-y-4">
                    <div class="flex items-center space-x-4">
                        <div class="p-2 bg-white rounded-full">
                            <!-- Icon from Heroicons (https://heroicons.com/) -->
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" data-slot="icon" class="w-6 h-6 text-blue-500">
                              <path d="M4.5 6.375a4.125 4.125 0 1 1 8.25 0 4.125 4.125 0 0 1-8.25 0ZM14.25 8.625a3.375 3.375 0 1 1 6.75 0 3.375 3.375 0 0 1-6.75 0ZM1.5 19.125a7.125 7.125 0 0 1 14.25 0v.003l-.001.119a.75.75 0 0 1-.363.63 13.067 13.067 0 0 1-6.761 1.873c-2.472 0-4.786-.684-6.76-1.873a.75.75 0 0 1-.364-.63l-.001-.122ZM17.25 19.128l-.001.144a2.25 2.25 0 0 1-.233.96 10.088 10.088 0 0 0 5.06-1.01.75.75 0 0 0 .42-.643 4.875 4.875 0 0 0-6.957-4.611 8.586 8.586 0 0 1 1.71 5.157v.003Z" />
                            </svg>
                        </div>
                        <div>
                            <div class="text-gray-200 text-sm">Najdeno št. rezultatov</div>
                            <div class="text-indigo-300 text-sm">Osebni trenerji</div>
                            <div class="text-white text-2xl font-semibold">
                                {{$cnt}}
                            </div>
                        </div>
                    </div>
                    <button class="w-full text-gray-900 bg-blue-200 hover:bg-blue-300 text-sm py-2 px-4 rounded-md transition duration-300 ease-in-out">
                        Vsi rezultati ({{$inc}})
                    </button>
                </div>
              </div>

            <!-- </div> -->

              <!-- Desktop -->
              <div class="hidden md:block">
                <div class="max-w-3xl mx-auto my-10">
                  @foreach($services as $service)
                     @if($service->type == 'Osebni trener')
                      <div class="mt-2 w-100 h-84 rounded-lg bg-gray-800 dark:bg-slate-800 shadow-md duration-300 hover:scale-105 hover:shadow-lg" style="display:flex;">
                        <img class="h-68 w-68 object-cover object-center" src="{{ asset('storage/images/services/'. $service->image) }}" alt="fitmentor" />
                        <div class="p-6">
                          <h2 class="mb-1 text-xl font-bold dark:text-white text-gray-200">{{ $service->title }}</h2>

                          <h3 class="text-lg font-normal dark:text-white text-gray-200">> {{ $service->region }},<!-- {{ $service->municipality }},--> {{ $service->city }}</h3>

                          <p class="text-semibold dark:text-gray-300 text-gray-200">{{ $service->description }}</p>

                          <p class="text-base dark:text-gray-300 text-gray-200">{{ $service->phone }}</p>

                          <a href="{{ $service->url }}"><p class="mb-2 text-blue-600">{{ $service->url }}</p></a>

                          <div class="flex items-center">
                            @if(!is_null($service->price))
                            <p class="mr-2 text-lg font-semibold text-gray-200 dark:text-white">
                            {{ $service->price }}€ / mes.
                            </p>
                            @else
                            <p class="mr-2 text-lg font-semibold text-white dark:text-white">
                            Po dogovoru
                            </p>
                            @endif
                          </div>
                        </div>
                      </div>
                      @endif
                  @endforeach
                  </div>
                </div>

                <!-- Hide this component on desktop -->
                  <div class="block md:hidden">
                    <div class="mb-4" style="display:grid; grid-template-columns: repeat(1, 1fr);
                          grid-gap: 10px;">

                          @auth
                          @foreach($services as $service)
                          <div class="mx-auto w-80 transform overflow-hidden rounded-lg bg-gray-800 dark:bg-slate-800 shadow-md duration-300 hover:scale-105 hover:shadow-lg">
                            <img class="h-64 w-full object-cover object-center" src="{{ asset('storage/images/services/'. $service->image) }}" alt="e-Storitve" />
                            <div class="p-4">
                              <h2 class="mb-1 text-xl font-bold dark:text-white text-gray-200">{{ $service->title }} ({{$service->user_id}})</h2>

                              <h3 class="mb-2 text-lg font-normal dark:text-white text-gray-200">> {{ $service->region }},<!-- {{ $service->municipality }},--> {{ $service->city }}</h3>

                              <p class="mb-2 text-semibold dark:text-gray-300 text-gray-200">{{ $service->description }}</p>

                              <p class="mb-2 text-base dark:text-gray-300 text-gray-200">{{ $service->phone }}</p>

                              <a href="{{ $service->url }}"><p class="mb-2 text-blue-600">{{ $service->url }}</p></a>

                              <div class="flex items-center">
                                @if(!is_null($service->price))
                                <p class="mr-2 text-lg font-semibold text-gray-200 dark:text-white">
                                {{ $service->price }}€
                                </p>
                                @else
                                <p class="mr-2 text-lg font-semibold text-white dark:text-white">
                                Po dogovoru
                                </p>
                                @endif
                              </div>
                            </div>
                          </div>
                          @endforeach

                          @else
                          @foreach($services as $service)
                          <div class="mx-auto w-80 transform overflow-hidden rounded-lg bg-gray-800 dark:bg-slate-800 shadow-md duration-300 hover:scale-105 hover:shadow-lg">
                            <img class="h-64 w-full object-cover object-center" src="{{ asset('storage/images/services/'. $service->image) }}" alt="e-Storitve" />
                            <div class="p-4">
                              <h2 class="mb-1 text-xl font-bold dark:text-white text-gray-200">{{ $service->title }}</h2>

                              <h3 class="mb-2 text-lg font-normal dark:text-white text-gray-200">> {{ $service->region }},<!-- {{ $service->municipality }},--> {{ $service->city }}</h3>

                              <p class="mb-2 text-semibold dark:text-gray-300 text-gray-200">{{ $service->description }}</p>

                              <p class="mb-2 text-base dark:text-gray-300 text-gray-200">{{ $service->phone }}</p>

                              <a href="{{ $service->url }}"><p class="mb-2 text-blue-600">{{ $service->url }}</p></a>

                              <div class="flex items-center">
                                @if(!is_null($service->price))
                                <p class="mr-2 text-lg font-semibold text-gray-200 dark:text-white">
                                {{ $service->price }}€
                                </p>
                                @else
                                <p class="mr-2 text-lg font-semibold text-white dark:text-white">
                                Po dogovoru
                                </p>
                                @endif

                              </div>
                            </div>
                          </div>
                          @endforeach
                          @endauth
                    </div>
                  </div>


              </div>

            <!-- Mobile -->
            <div class="block md:hidden">
              <h1 class="text-2xl font-semibold text-black text-center">
                FITMENTOR | Vizija
              </h1>
              <p class="mb-2 mt-2 text-semibold dark:text-gray-300 text-black text-center">
                Hitro in enostavno do osebnega trenerja, ki vam bo pomagal pri uresničitvi vaših ciljev na področju fitnesa in športnih aktivnosti.
                <br /><br />
                Naš portal zagotavlja in redno preverja kakovostne standarde osebnih trenerjev, zato ste lahko prepričani, da boste sodelovali z strokovnjaki na teh področjih.
                <br /><br />
                Za vpis v našo evidenco osebnih trenerjev morate izpolnjevati določene pogoje, ki jih pridobite neposredno od nas na zahtevo (prijave sprejemamo na naš e-mail naslov).
              </p>
            </div>

        </div>

    <!-- Izpostavljeno -->





    <!-- Mobile -->
  <div class="block md:hidden">
    <h1 class="text-2xl text-center font-semibold text-gray-900 mb-2">
      Kakšni so vaši cilji?
    </h1>
      <div class="flex flex-col">
        <div class="flex justify-center items-center w-45 ml-12 mr-12">
         <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
           <div class="h-full w-full">
               <div class="relative w-full">
                   <img src="https://cdn.pixabay.com/photo/2021/01/13/16/46/workout-5914643_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
                   <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-500 p-2 text-brand-500 hover:cursor-pointer">
                   </button>
               </div>
               <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                   <div class="mb-2">
                       <p class="text-lg font-bold text-navy-700"> Izgubiti težo </p>
                   </div>
                   <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                       <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🏃🏼‍♀️</span>
                   </div>
               </div>
               <div class="flex items-center justify-between md:items-center lg:justify-between ">
                   <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Turizem">Išči</a></button>
               </div>
           </div>
        </div>
       </div>
      </div>

      <div class="flex flex-col mt-6">
        <div class="flex justify-center items-center w-45 ml-12 mr-12">
         <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
           <div class="h-full w-full">
            <div class="relative w-full">
              <img src="https://cdn.pixabay.com/photo/2015/11/01/19/45/weights-1017465_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
              <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-500 p-2 text-brand-500 hover:cursor-pointer">
              </button>
            </div>
               <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                   <div class="mb-2">
                       <p class="text-lg font-bold text-navy-700"> Pridobiti mišično maso </p>
                   </div>
                   <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                       <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🏋️‍♀️</span>
                   </div>
               </div>
               <div class="flex items-center justify-between md:items-center lg:justify-between ">
                   <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Turizem">Išči</a></button>
               </div>
           </div>
        </div>
       </div>
      </div>

      <div class="flex flex-col mt-6">
        <div class="flex justify-center items-center w-45 ml-12 mr-12">
         <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
            <div class="h-full w-full">
              <div class="relative w-full">
              <img src="https://cdn.pixabay.com/photo/2017/04/26/09/44/sport-2262083_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
              <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-500 p-2 text-brand-500 hover:cursor-pointer">
              </button>
          </div>
               <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                   <div class="mb-2">
                       <p class="text-lg font-bold text-navy-700"> Povečati vzdržljivost </p>
                   </div>
                   <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                       <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🚴‍♀️</span>
                   </div>
               </div>
               <div class="flex items-center justify-between md:items-center lg:justify-between ">
                   <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Turizem">Išči</a></button>
               </div>
           </div>
        </div>
       </div>
      </div>

      <div class="flex flex-col mt-6">
        <div class="flex justify-center items-center w-45 ml-12 mr-12">
         <div class="!z-5 relative flex flex-col rounded-[20px] max-w-[300px] bg-white bg-clip-border shadow-3xl shadow-shadow-500 flex flex-col w-full !p-4 3xl:p-![18px] bg-white undefined">
           <div class="h-full w-full">
            <div class="relative w-full">
              <img src="https://cdn.pixabay.com/photo/2015/07/02/10/27/training-828764_1280.jpg" class="mb-3 h-full w-full rounded-xl 3xl:h-full 3xl:w-full" alt="">
                  <button class="absolute top-3 right-3 flex items-center justify-center rounded-full bg-green-300 p-2 text-brand-500 hover:cursor-pointer">
                      <div class="flex h-full w-full items-center justify-center rounded-full text-xl hover:bg-gray-50">
                      </div>
                  </button>
              </div>
               <div class="mb-3 flex items-center justify-between px-1 md:items-start">
                   <div class="mb-2">
                       <p class="text-lg font-bold text-navy-700"> Zdrav življenski slog </p>
                   </div>
                   <div class="flex flex-row-reverse md:mt-2 lg:mt-0">
                       <span class="z-0 ml-px inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-[#E0E5F2] text-xs text-navy-700 ">🤸‍♂️</span>
                   </div>
               </div>
               <div class="flex items-center justify-between md:items-center lg:justify-between ">
                   <button href="" class="linear rounded-[20px] bg-brand-900 px-4 py-2 text-base font-medium text-white transition duration-200 hover:bg-brand-800 active:bg-brand-700"><a href="/type?search=Turizem">Išči</a></button>
               </div>
           </div>
        </div>
       </div>
      </div>


   </div>




          <!-- Mobile -->
          <div class="block md:hidden">
            <h1 class="text-2xl font-semibold text-black text-center">
              FITMENTOR | Vizija
            </h1>
            <p class="mb-2 mt-2 text-semibold dark:text-gray-300 text-black text-center">
              Hitro in enostavno do osebnega trenerja, ki vam bo pomagal pri uresničitvi vaših ciljev na področju fitnesa in športnih aktivnosti.
              <br /><br />
              Naš portal zagotavlja in redno preverja kakovostne standarde osebnih trenerjev, zato ste lahko prepričani, da boste sodelovali z strokovnjaki na teh področjih.
              <br /><br />
              Za vpis v našo evidenco osebnih trenerjev morate izpolnjevati določene pogoje, ki jih pridobite neposredno od nas na zahtevo (prijave sprejemamo na naš e-mail naslov).
            </p>
          </div>



            <div class="flex items-center justify-center p-3 mr-2 ml-2 w-82 border-gray-300" role="alert">
                <h1 class="text-4xl font-semibold text-gray-900">
                  Trenutno aktualno
                </h1>
            </div>

   <!-- Show this component on mobile -->
   <div class="block md:hidden text-center mt-5">

   <form class="w-full rounded-md px-3 py-1 flex items-center" action="{{url('type')}}" method="get">
          <select id="type" name="search" class="w-full rounded-md border border-[#DDE2E4] px-3 py-2 text-sm" type="{{ url('search') }}" name="type">
            @php
                $dropdownValues = ['Izguba telesne teže',
            'Pridobitev mišične mase',
            'Vzdržljivost in kondicija',
            'Zdrav življenjski slog',
            'Sprostitvena vadba',
            'Vadba za moč',
            'Fitnes studio',
            'Drugo'];
            @endphp

            @foreach($dropdownValues as $value)
                <option value="{{ $value }}">{{ $value }}</option>
            @endforeach
          </select>
          <button type="submit" class="ml-2 btn btn-primary">
        <i class="fa fa-search"></i>
          </button>
          </form>

          <form class="w-full rounded-md px-3 py-1 flex items-center" action="{{url('region')}}" method="get">
          <select id="region" name="search" class="w-full rounded-md border border-[#DDE2E4] px-3 py-2 text-sm" type="{{ url('search') }}">
            @php
                $dropdownValues = ['Regija',
            'Gorenjska',
            'Goriška',
            'Jugovzhodna Slovenija',
            'Koroška',
            'Notranjsko-kraška',
            'Obalno-kraška',
            'Osrednjeslovenska',
            'Podravska',
            'Pomurska',
            'Posavska',
            'Primorsko-notranjska',
            'Savinjska',
            'Zasavska'];
            @endphp
            @foreach($dropdownValues as $value)
                <option value="{{ $value }}">{{ $value }}</option>
            @endforeach
          </select>
          <button type="submit" class="ml-2 btn btn-primary">
        <i class="fa fa-search"></i>
          </button>
          </form>

          <form class="w-full rounded-md px-3 py-1 flex items-center" action="{{url('search')}}" method="get">
          <input type="{{ url('search') }}" name="search" class="w-full rounded-md border border-[#DDE2E4] px-3 py-2 text-sm" placeholder="Naziv storitve..." />
          <button type="submit" class="ml-2 btn btn-primary">
        <i class="fa fa-search"></i>
          </button>

          </form>

    </div>

  <!-- Show this component on desktop -->
  <div class="hidden md:block">
  <div class="" style="display:grid; grid-template-columns: repeat(4, 1fr);
          grid-gap: 10px;">

      @php
      $st = 0;
      @endphp

          @foreach($services as $service)

          @php
              $st++;
          @endphp

            @if($st > 4)
                @break
            @endif

          <div class="mx-auto mt-6 w-80 transform overflow-hidden rounded-lg bg-gray-800 dark:bg-slate-800 shadow-md duration-300 hover:scale-105 hover:shadow-lg">
            <img class="h-64 w-full object-cover object-center" src="{{ asset('storage/images/services/'. $service->image) }}" alt="e-Storitve.com" />
            <div class="p-4">
              <h2 class="mb-1 text-xl font-bold dark:text-white text-gray-200">{{ $service->title }} ({{$service->user_id}})</h2>

              <h3 class="mb-2 text-lg font-normal dark:text-white text-gray-200">> {{ $service->region }},<!-- {{ $service->municipality }},--> {{ $service->city }}</h3>

              <p class="mb-2 text-semibold dark:text-gray-300 text-gray-200">{{ $service->description }}</p>

              <p class="mb-2 text-base dark:text-gray-300 text-gray-200">{{ $service->phone }}</p>

              <a href="{{ $service->url }}"><p class="mb-2 text-blue-600">{{ $service->url }}</p></a>

              <div class="flex items-center">
                @if(!is_null($service->price))
                <p class="mr-2 text-lg font-semibold text-gray-200 dark:text-white">
                {{ $service->price }}€
                </p>
                @else
                <p class="mr-2 text-lg font-semibold text-white dark:text-white">
                Po dogovoru
                </p>
                @endif
              </div>
              <div class="flex items-center mt-1 text-white">
              {{$service->type}}
              </div>
            </div>
          </div>
          @endforeach

  </div>
  </div>

  <!-- Hide this component on desktop -->
  <div class="block md:hidden">
   <div class="" style="display:grid; grid-template-columns: repeat(1, 1fr);
          grid-gap: 10px;">

          @auth
          @foreach($services as $service)
          <div class="mx-auto mt-11 w-80 transform overflow-hidden rounded-lg bg-gray-800 dark:bg-slate-800 shadow-md duration-300 hover:scale-105 hover:shadow-lg">
            <img class="h-64 w-full object-cover object-center" src="{{ asset('storage/images/services/'. $service->image) }}" alt="e-Storitve" />
            <div class="p-4">
              <h2 class="mb-1 text-xl font-bold dark:text-white text-gray-200">{{ $service->title }} ({{$service->user_id}})</h2>

              <h3 class="mb-2 text-lg font-normal dark:text-white text-gray-200">> {{ $service->region }},<!-- {{ $service->municipality }},--> {{ $service->city }}</h3>

              <p class="mb-2 text-semibold dark:text-gray-300 text-gray-200">{{ $service->description }}</p>

              <p class="mb-2 text-base dark:text-gray-300 text-gray-200">{{ $service->phone }}</p>

              <a href="{{ $service->url }}"><p class="mb-2 text-blue-600">{{ $service->url }}</p></a>

              <div class="flex items-center">
                @if(!is_null($service->price))
                <p class="mr-2 text-lg font-semibold text-gray-200 dark:text-white">
                {{ $service->price }}€
                </p>
                @else
                <p class="mr-2 text-lg font-semibold text-white dark:text-white">
                Po dogovoru
                </p>
                @endif
              </div>
            </div>
          </div>
          @endforeach

          @else
          @foreach($services as $service)
          <div class="mx-auto mt-11 w-80 transform overflow-hidden rounded-lg bg-gray-800 dark:bg-slate-800 shadow-md duration-300 hover:scale-105 hover:shadow-lg">
            <img class="h-64 w-full object-cover object-center" src="{{ asset('storage/images/services/'. $service->image) }}" alt="e-Storitve" />
            <div class="p-4">
              <h2 class="mb-1 text-xl font-bold dark:text-white text-gray-200">{{ $service->title }}</h2>

              <h3 class="mb-2 text-lg font-normal dark:text-white text-gray-200">> {{ $service->region }},<!-- {{ $service->municipality }},--> {{ $service->city }}</h3>

              <p class="mb-2 text-semibold dark:text-gray-300 text-gray-200">{{ $service->description }}</p>

              <p class="mb-2 text-base dark:text-gray-300 text-gray-200">{{ $service->phone }}</p>

              <a href="{{ $service->url }}"><p class="mb-2 text-blue-600">{{ $service->url }}</p></a>

              <div class="flex items-center">
                @if(!is_null($service->price))
                <p class="mr-2 text-lg font-semibold text-gray-200 dark:text-white">
                {{ $service->price }}€
                </p>
                @else
                <p class="mr-2 text-lg font-semibold text-white dark:text-white">
                Po dogovoru
                </p>
                @endif

              </div>
            </div>
          </div>
          @endforeach
          @endauth
    </div>
  </div>
</div>

            <div class="justify-center items-center text-center pt-3 pb-5 text-xl border-t border-b border-gray-300 font-semibold mt-5">
                <p class="pb-2">Sledite nam na:</p>
                <a href="https://www.facebook.com/groups/estoritve"><i class="fa fa-facebook ml-2 mr-2 text-blue-700"></i></a>
                <a href="https://www.instagram.com/estoritve/"><i class="fa fa-instagram ml-2 mr-2 text-pink-900"></i></a>
            </div>

    <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>

    <br />
    <footer class="bg-gray-800 text-black pt-4 pb-4">
              <div class="text-white" style="text-align: center;">
                  <p class="font-bold mb-1">&copy; 2024 FitMentor.si | Športno-mentorske dejavnosti in storitve</p>
                  <p>Izvajanje storitev ter transakcije so prepuščene posameznikom, spletni portal ni odgovoren za morebitne izgube ali težave pri izvajanju storitev</p>
              </div>
    </footer>
</body>
</html>
